service: template

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

  stage: dev
  region: ap-northeast-1

# you can add statements to the Lambda function's IAM Role here
  iam:
    role: arn:aws:iam::250172214346:role/lambda-s3-role
  environment:
    s3_bucket: online-data-lake-thirty-three

  layers:
    - arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-p39-requests:13
    - arn:aws:lambda:ap-northeast-1:336392948345:layer:AWSSDKPandas-Python39:6

# package:
#   individually: True

functions:
  somefunction:
    handler: handler.somefunction
    timeout: 180
    memorySize: 256
    # layers:
    #   - arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-p39-requests:13
    #   - arn:aws:lambda:ap-northeast-1:336392948345:layer:AWSSDKPandas-Python39:6

  get_tdx_link_id:
    handler: handler.get_tdx_link_id
    timeout: 120
    memorySize: 256
    # layers:
    #   - arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-p39-requests:13
    #   - arn:aws:lambda:ap-northeast-1:336392948345:layer:AWSSDKPandas-Python39:6

