service: tdx-bus-route

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

  stage: dev
  region: ap-northeast-1

# you can add statements to the Lambda function's IAM Role here
  iam:
    role: arn:aws:iam::250172214346:role/lambda-s3-role
  environment:
    s3_bucket: online-data-lake-thirty-three
    tdx_auth_url: https://tdx.transportdata.tw/auth/realms/TDXConnect/protocol/openid-connect/token
    tdx_client_id: unhuman_7932-b91de074-ceed-4ef1
    tdx_client_secret: 7425e597-8f32-4d9e-a8b4-da2a5606c2b8

  layers:
    - arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-p39-requests:13
    - arn:aws:lambda:ap-northeast-1:336392948345:layer:AWSSDKPandas-Python39:6

# package:
#   individually: True

functions:
  get_tdx_bus_route:
    handler: handler.get_tdx_bus_route
    timeout: 180
    memorySize: 128
    # layers:
    #   - arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-p39-requests:13
    #   - arn:aws:lambda:ap-northeast-1:336392948345:layer:AWSSDKPandas-Python39:6


